put contents of git-ready in a main loop to prepare for other changes

diff --git a/bin/git-ready b/bin/git-ready
--- a/bin/git-ready
+++ b/bin/git-ready
@@ -2,36 +2,40 @@
 
 . $SKIGGETY_UTILS_DIR/lib/skiggety-utils.bash
 
-while [[ "$1" == -* ]]; do
-    # accept -n for git commit -n
-    if [ "$1" == "-n" ]; then
-        GIT_COMMIT_OPTIONS="$GIT_COMMIT_OPTIONS $1"
-        shift
-    else
-        exit_with_error "option not supported: $1"
-    fi
-done
+function main {
+    while [[ "$1" == -* ]]; do
+        # accept -n for git commit -n
+        if [ "$1" == "-n" ]; then
+            GIT_COMMIT_OPTIONS="$GIT_COMMIT_OPTIONS $1"
+            shift
+        else
+            exit_with_error "option not supported: $1"
+        fi
+    done
 
-# TODO^5: un-loop:
-# TODO^8: git vimdiff --staged should be optional
-# TODO^2: if the remote branch doesn't exist yet, we should skip trying git pull, since it will fail anyway
-# TODO: stop before vimdiff if there is no git diff
-for command in \
-    'git add -p' \
-    'git vimdiff --staged' \
-    "git commit $GIT_COMMIT_OPTIONS" \
-    'git pull' \
-    'git push -u'
-do
-    # TODO^4: method extract, or even script extract "run_with_hesitation":
+    # TODO^5: un-loop:
+    # TODO^9: git vimdiff --staged should be optional
+    # TODO^2: if the remote branch doesn't exist yet, we should skip trying git pull, since it will fail anyway
+    # TODO: stop before vimdiff if there is no git diff
+    for command in \
+        'git add -p' \
+        'git vimdiff --staged' \
+        "git commit $GIT_COMMIT_OPTIONS" \
+        'git pull' \
+        'git push -u'
+    do
+        # TODO^6: method extract, or even script extract "run_with_hesitation":
+        echo
+        echo "running \"$command\" momentarily, press CTRL+C to stop..."
+        sleep-verbose 2
+        $command || exit_with_error "Command \"$command\" failed."
+    done
+
     echo
-    echo "running \"$command\" momentarily, press CTRL+C to stop..."
-    sleep-verbose 2
-    $command || exit_with_error "Command \"$command\" failed."
-done
+    git -c color.ui=always --no-pager log --oneline --decorate=short origin/HEAD~..HEAD -n 3
 
-echo
-git -c color.ui=always --no-pager log --oneline --decorate=short origin/HEAD~..HEAD -n 3
+    echo
+    echo "...finished '$(basename "$0")'."
+}
 
-echo
-echo "...finished '$(basename "$0")'."
+main "$@"
