in dev script, get to the current experiment right away

diff --git a/PWD_BIN/dev b/PWD_BIN/dev
--- a/PWD_BIN/dev
+++ b/PWD_BIN/dev
@@ -13,12 +13,6 @@ THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
 
 echo_divider_with_text "#" "running 'dev':"
 
-unit-test && echo "unit-test SUCCEEDED" || exit_with_error "unit-test FAILED"
-
-lint && echo "lint SUCCEEDED" || exit_with_error "lint FAILED"
-
-dashboard || accumulate_error "dashboard FAILED"
-
 # TODO^2: ask Kevin to test if this generation is working for him and if it shows up in his 'todo' output:
 experiment_script="./PWD_BIN/experiment.gitignored.bash"
 if ! [ -f "$experiment_script" ]; then
@@ -33,9 +27,15 @@ fi
 
 if [ -f "$experiment_script" ]; then
     echo_divider_with_text "=" "Running \"$experiment_script\" ..."
-    $experiment_script || accumulate_error "experimental script \"$experiment_script\" FAILED"
+    $experiment_script || exit_with_error "experimental script \"$experiment_script\" FAILED"
     echo_divider_with_text "=" "...DONE running \"$experiment_script\" ."
 fi
+
+unit-test && echo "unit-test SUCCEEDED" || exit_with_error "unit-test FAILED"
+
+lint && echo "lint SUCCEEDED" || exit_with_error "lint FAILED"
+
+dashboard || accumulate_error "dashboard FAILED"
 
 echo_divider_with_text "#" "END of 'dev'."
 exit_with_any_accumulated_errors
