adjust some todo's

diff --git a/PWD_BIN/install b/PWD_BIN/install
--- a/PWD_BIN/install
+++ b/PWD_BIN/install
@@ -94,7 +94,7 @@ function use_installer {
         # TODO TODO TODO: get really into editable vim macros (and/or emacs, just to try it)
     else
         echo "Running installer \"$installer\":"
-        $installer_path $INSTALLER_ARGS || exit_with_error "$installer failed"
+        $installer_path $INSTALLER_ARGS || exit_with_error "$installer failed" # TODO TODO TODO: if installer fails, count it as a failure in a variable "$cumulative_exit_status" and exit on error later, with a suggestion to re-run "install" manually
     fi
 }
 
