WIP on firstlife poc

diff --git a/PWD_BIN/lint b/PWD_BIN/lint
--- a/PWD_BIN/lint
+++ b/PWD_BIN/lint
@@ -13,6 +13,13 @@ echo_divider_with_text "O-=======-" "lint:"
 echo_divider_with_text "+-=======-" "collapse todo votes:"
 todo -wfq --non-interactive --exclude-dir .git || accumulate_error "could not write simplified TODO entries, todo exited with $?" # IGNORE_TODO
 
+if [ -d $HOME/firstlife ]; then
+    pushd $HOME/firstlife > /dev/null
+    echo_divider_with_text "+-=======-" "collapse todo votes in $PWD:"
+    $SKIGGETY_UTILS_DIR/bin/todo -wfq --exclude-dir log --non-interactive || accumulate_error "could not write simplified TODO entries for firstlife, todo exited with $?" # IGNORE_TODO
+    popd > /dev/null
+fi
+
 echo_divider_with_text "+-=======-" "generate ./todo_report/README.txt:"
 generate_todo_report >/dev/null || accumulate_error 'could not generate todo report'
 echo "The most important todo is currently:"
